# Generated by Django 6.1 on 2026-08-21 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Latching Techniques', 'Latching Techniques'), ('Milk Storage & Safety', 'Milk Storage & Safety'), ('Maternal Nutrition', 'Maternal Nutrition'), ('Newborn Health', 'Newborn Health')], max_length=50)),
                ('read_time', models.CharField(help_text='Display string, e.g. "5 min read"', max_length=50)),
                ('teaser', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=150)),
                ('rating', models.CharField(default='4.9 ★', max_length=20)),
                ('evidence_label', models.CharField(default='Organization-Verified & Peer-Reviewed', max_length=255)),
                ('date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_reported', models.BooleanField(default=False)),
                ('report_reason', models.CharField(blank=True, choices=[('Spam', 'Spam'), ('Inappropriate', 'Inappropriate'), ('Misinformation', 'Misinformation'), ('Other', 'Other')], max_length=20)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='articles.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
