# Generated by Django 6.1 on 2026-08-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('url', models.URLField()),
                ('type', models.CharField(choices=[('Video', 'Video'), ('Infographic', 'Infographic')], max_length=20)),
            ],
        ),
    ]
