# Generated by Django 6.1 on 2026-09-05 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='current_model',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='model_switched',
        ),
    ]
