# Generated by Django 6.1 on 2026-09-25 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_chatsession_current_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('citation', models.CharField(help_text='Full reference as it should be cited, e.g. "WHO (2023). Infant and young child feeding."', max_length=500)),
                ('content', models.TextField(help_text='The reviewed text itself. Plain text; blank lines separate paragraphs.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to withdraw a source from retrieval without deleting it.')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_kind', models.CharField(choices=[('article', 'Verified article'), ('literature', 'Reviewed literature')], max_length=20)),
                ('source_id', models.PositiveIntegerField()),
                ('source_title', models.CharField(max_length=255)),
                ('source_reference', models.CharField(blank=True, help_text='Article category, or the literature citation.', max_length=500)),
                ('ordinal', models.PositiveIntegerField(help_text='Position of this passage within its source document.')),
                ('text', models.TextField()),
                ('embedding', models.JSONField(blank=True, default=list, help_text='Embedding vector, or [] when not embedded yet -- such a chunk is still retrievable lexically.')),
                ('embedding_model', models.CharField(blank=True, help_text="Which model produced `embedding`. A change here invalidates the vector, since similarities are only comparable within one model's space.", max_length=100)),
                ('source_revision', models.CharField(max_length=64)),
                ('indexed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['source_kind', 'source_id', 'ordinal'],
                'indexes': [models.Index(fields=['source_kind', 'source_id'], name='chat_knowle_source__9cd3c0_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_kind', 'source_id', 'ordinal'), name='unique_chunk_per_source_position')],
            },
        ),
    ]
