# Generated by Django 6.1 on 2026-10-01 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_knowledgedocument_knowledgechunk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at', 'id']},
        ),
    ]
