# Generated by Django 6.1 on 2026-08-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Accredited Human Milk Bank', 'Accredited Human Milk Bank'), ('Hospital Depot', 'Hospital Depot')], max_length=100)),
                ('contact', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=500)),
                ('operating_hours', models.CharField(default='8:00 AM - 5:00 PM (Mon-Fri)', max_length=100)),
                ('donor_requirements', models.TextField(blank=True)),
                ('recipient_requirements', models.TextField(blank=True)),
                ('unavailable_donor_dates', models.JSONField(blank=True, default=list)),
                ('unavailable_recipient_dates', models.JSONField(blank=True, default=list)),
                ('is_operational', models.BooleanField(default=True)),
                ('capacity', models.PositiveIntegerField(help_text='Total booking slots this facility can handle')),
                ('booked_count', models.PositiveIntegerField(default=0, help_text='Slots currently booked. Set by hand until Phase 4 derives it from real MilkBankRequest rows.')),
                ('stock_level_ml', models.PositiveIntegerField(default=0, help_text='Current stored milk volume, in mL')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
