# Generated by Django 6.1 on 2026-08-21 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkbank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkBankRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('DONOR', 'Donor'), ('RECIPIENT', 'Recipient')], max_length=20)),
                ('current_stage_index', models.PositiveIntegerField(default=0)),
                ('current_sub_status', models.CharField(choices=[('pending', 'Pending'), ('awaiting_attendance', 'Awaiting Attendance'), ('scheduled', 'Scheduled'), ('declined', 'Declined'), ('expired', 'Expired'), ('counter_offered', 'Counter Offer'), ('completed', 'Completed')], default='pending', max_length=30)),
                ('staff_message', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.CharField(max_length=20)),
                ('attendance_confirmed', models.BooleanField(default=False)),
                ('counter_offer_date', models.DateField(blank=True, null=True)),
                ('counter_offer_time', models.CharField(blank=True, max_length=20)),
                ('allocated_facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='milkbank.facility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milkbank_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Donation', 'Donation'), ('Received', 'Received')], max_length=20)),
                ('facility_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Completed', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
