# Generated by Django 6.1 on 2026-08-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkbank', '0002_milkbankrequest_transactionrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='booked_count',
            field=models.PositiveIntegerField(default=0, help_text='Slots currently booked. Kept in sync automatically as requests are created/close out -- see milkbank/transitions.py -- but still editable by hand in admin, e.g. to seed a starting count before any real bookings exist.'),
        ),
    ]
