# Generated by Django 6.1 on 2026-08-29 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkbank', '0003_alter_facility_booked_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currently_lactating_excess', models.BooleanField(help_text="Currently lactating and producing milk beyond own infant's needs")),
                ('infant_age_months', models.PositiveIntegerField(help_text="Age of donor's own infant, in months")),
                ('consents_to_screening', models.BooleanField(help_text='Consents to blood screening and to donating voluntarily, without payment')),
                ('good_general_health', models.BooleanField()),
                ('being_treated_for_illness', models.BooleanField(help_text='Being treated for any acute or chronic illness')),
                ('recent_fever_or_infection', models.BooleanField(help_text='Fever or active infection in the past week')),
                ('tested_positive_infectious_disease', models.BooleanField(help_text='Ever tested positive for HIV 1/2, HTLV 1/2, Hepatitis B, Hepatitis C, or syphilis')),
                ('partner_tested_positive_or_at_risk', models.BooleanField(help_text='Sexual partner ever tested positive for, or at risk of, HIV or hepatitis')),
                ('recent_blood_transfusion', models.BooleanField(help_text='Blood transfusion or blood products in the past 12 months')),
                ('recent_tattoo_piercing_needle_exposure', models.BooleanField(help_text='Tattoo, piercing, or accidental needle-stick exposure in the past 12 months')),
                ('travel_to_risk_area', models.BooleanField(help_text='Traveled to/lived in an area with risk of relevant transmissible disease (per DOH advisories)')),
                ('smokes_or_tobacco', models.BooleanField()),
                ('drinks_alcohol', models.BooleanField()),
                ('alcohol_frequency_details', models.CharField(blank=True, help_text='How often and how much', max_length=255)),
                ('uses_illicit_drugs', models.BooleanField()),
                ('on_prescription_medications', models.BooleanField()),
                ('medication_list', models.TextField(blank=True)),
                ('uses_herbal_supplements', models.BooleanField(help_text='Herbal supplements, megadose vitamins, or botanical products')),
                ('uses_radioactive_or_radiologic', models.BooleanField(help_text='Radioactive substances or undergoing radiologic treatment')),
                ('vegan_without_b12', models.BooleanField(help_text='Diet excludes all animal products without B12 supplementation')),
                ('recent_live_virus_vaccine', models.BooleanField(help_text='Recently received any live-virus vaccines')),
                ('serology_photo', models.FileField(blank=True, null=True, upload_to='serology_photos/%Y/%m/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donor_questionnaire', to='milkbank.milkbankrequest')),
            ],
        ),
    ]
