# Generated by Django 6.1 on 2026-09-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkbank', '0004_donorquestionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkbankrequest',
            name='response_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
