# Generated by hand (non-interactive makemigrations can't ask for a
# one-off default) on 2026-09-19.
#
# Re-shapes DonorQuestionnaire to match the mobile app's actual 7-question
# donor screening form field-for-field -- see milkbank/models.py's
# DonorQuestionnaire docstring. The removed fields belonged to a longer
# clinical form the mobile app never asked and never submitted (see the
# bug this fixes: the app never POSTed to this endpoint at all), so there
# is nothing real to preserve across the rename/removal.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkbank', '0005_milkbankrequest_response_deadline'),
    ]

    operations = [
        migrations.RemoveField(model_name='donorquestionnaire', name='currently_lactating_excess'),
        migrations.RemoveField(model_name='donorquestionnaire', name='infant_age_months'),
        migrations.RemoveField(model_name='donorquestionnaire', name='consents_to_screening'),
        migrations.RemoveField(model_name='donorquestionnaire', name='being_treated_for_illness'),
        migrations.RemoveField(model_name='donorquestionnaire', name='recent_fever_or_infection'),
        migrations.RemoveField(model_name='donorquestionnaire', name='tested_positive_infectious_disease'),
        migrations.RemoveField(model_name='donorquestionnaire', name='partner_tested_positive_or_at_risk'),
        migrations.RemoveField(model_name='donorquestionnaire', name='recent_blood_transfusion'),
        migrations.RemoveField(model_name='donorquestionnaire', name='recent_tattoo_piercing_needle_exposure'),
        migrations.RemoveField(model_name='donorquestionnaire', name='travel_to_risk_area'),
        migrations.RemoveField(model_name='donorquestionnaire', name='smokes_or_tobacco'),
        migrations.RemoveField(model_name='donorquestionnaire', name='drinks_alcohol'),
        migrations.RemoveField(model_name='donorquestionnaire', name='alcohol_frequency_details'),
        migrations.RemoveField(model_name='donorquestionnaire', name='uses_illicit_drugs'),
        migrations.RemoveField(model_name='donorquestionnaire', name='on_prescription_medications'),
        migrations.RemoveField(model_name='donorquestionnaire', name='medication_list'),
        migrations.RemoveField(model_name='donorquestionnaire', name='uses_herbal_supplements'),
        migrations.RemoveField(model_name='donorquestionnaire', name='uses_radioactive_or_radiologic'),
        migrations.RemoveField(model_name='donorquestionnaire', name='vegan_without_b12'),
        migrations.RemoveField(model_name='donorquestionnaire', name='recent_live_virus_vaccine'),
        migrations.AlterField(
            model_name='donorquestionnaire',
            name='good_general_health',
            field=models.BooleanField(help_text='Currently in good general health'),
        ),
        migrations.AddField(
            model_name='donorquestionnaire',
            name='lactating_with_excess_supply',
            field=models.BooleanField(
                default=False,
                help_text='Baby is under 6 months old and producing more milk than baby needs',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donorquestionnaire',
            name='free_of_infectious_disease',
            field=models.BooleanField(
                default=False,
                help_text='Free from HIV, Hepatitis B & C, and Syphilis',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donorquestionnaire',
            name='recent_transfusion_or_transplant',
            field=models.BooleanField(
                default=False,
                help_text='Received a blood transfusion or organ transplant in the last 12 months',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donorquestionnaire',
            name='uses_tobacco_alcohol_or_drugs',
            field=models.BooleanField(
                default=False,
                help_text='Smokes, drinks alcohol regularly, or uses recreational drugs',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donorquestionnaire',
            name='on_medication_or_supplements',
            field=models.BooleanField(
                default=False,
                help_text='Taking regular medications or herbal supplements',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donorquestionnaire',
            name='medication_details',
            field=models.CharField(blank=True, help_text='Medications / supplements', max_length=255),
        ),
        migrations.AddField(
            model_name='donorquestionnaire',
            name='has_recent_serology_test',
            field=models.BooleanField(
                default=False,
                help_text='Has a serological (blood) test taken within the last 6 months',
            ),
            preserve_default=False,
        ),
    ]
