# Generated by Django 6.1 on 2026-09-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkbank', '0006_donorquestionnaire_match_mobile_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkbankrequest',
            name='needs_representative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='milkbankrequest',
            name='representative_birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milkbankrequest',
            name='representative_contact_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='milkbankrequest',
            name='representative_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
