# Generated by Django 6.1 on 2026-09-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkbank', '0007_milkbankrequest_needs_representative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkbankrequest',
            name='amount_ml',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milkbankrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
