# Generated by Django 6.1 on 2026-09-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkbank', '0008_milkbankrequest_amount_ml_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrecord',
            name='amount_ml',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
