# Generated by Django 6.1 on 2026-09-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkbank', '0009_transactionrecord_amount_ml'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkbankrequest',
            name='clinic_info',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='milkbankrequest',
            name='has_cooler',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='milkbankrequest',
            name='has_medical_abstract',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='milkbankrequest',
            name='has_prescription_proof',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='milkbankrequest',
            name='neonate_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
