# Generated by Django 6.1 on 2026-08-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_last_active_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_seen_walkthrough',
            field=models.BooleanField(default=False),
        ),
    ]
