# Generated by Django 6.1 on 2026-09-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_password_reset_attempts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(help_text='Already hashed -- never a plaintext password.', max_length=128)),
                ('mom_name', models.CharField(blank=True, max_length=150)),
                ('baby_name', models.CharField(blank=True, max_length=150)),
                ('code', models.CharField(max_length=6)),
                ('sent_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verification_attempts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verification_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verification_sent_at',
        ),
    ]
