# Generated by Django 6.1 on 2026-09-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_pendingregistration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingregistration',
            name='code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
