# Generated by Django 6.1 on 2026-09-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_pendingregistration_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_received_ml',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
